name: Update Contributors Grid

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write  # this allows pushing to the repo

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Contributors Grid
        run: |
          GRID_FILE="contributors_grid.md"
          echo "<table><tr>" > $GRID_FILE
          COUNT=0
          MAX_PER_ROW=6

          # Read GitHub URLs from CONTRIBUTORS.md and generate grid
          grep -oP '\(https://github.com/[^)]+\)' CONTRIBUTORS.md | tr -d '()' | while read url; do
            username=$(basename "$url")

            echo "<td align=\"center\" width=\"125\">" >> $GRID_FILE
            echo "  <a href=\"$url\">" >> $GRID_FILE
            echo "    <img src=\"$url.png?size=96\" width=\"96\" height=\"96\" alt=\"$username\"/><br/>" >> $GRID_FILE
            echo "    <sub><b>$username</b></sub>" >> $GRID_FILE
            echo "  </a>" >> $GRID_FILE
            echo "</td>" >> $GRID_FILE


            COUNT=$((COUNT+1))
            if [ $COUNT -ge $MAX_PER_ROW ]; then
              echo "</tr><tr>" >> $GRID_FILE
              COUNT=0
            fi
          done

          echo "</tr></table>" >> $GRID_FILE

          # Replace between markers in README.md safely
          awk '
            BEGIN {inside=0}
            /<!-- CONTRIBUTORS START -->/ {print; system("cat contributors_grid.md"); inside=1; next}
            /<!-- CONTRIBUTORS END -->/ {inside=0}
            !inside {print}
          ' README.md > README.tmp && mv README.tmp README.md
      - name: Commit and Push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "Update contributors grid" || echo "No changes to commit"
          git push
